### ISSUE TITLE
docs - don't use smartquotes

### ISSUE THREAD

**Issue by dcsan** [botorange/xiaoju#11]
the docs sent to me are using smartquotes which breaks the code "
I guess it was pasted in word or mac Notes app which converted it all...

> “ ≠ "

![image](https://user-images.githubusercontent.com/514002/59431297-27860f80-8e17-11e9-942d-a5bded1c7f2a.png)

after

![image](https://user-images.githubusercontent.com/514002/59431346-47b5ce80-8e17-11e9-9cc6-73d77d53a6f0.png)

**Comment by iguxiaobei** [comment]
we have corrected it.

please check the latest doc.
[latest doc](https://github.com/juzibot/xiaoju/wiki/API-Doc)

@dcsan
