### ISSUE TITLE
send message api error messageType is not integer

### ISSUE THREAD

**Issue by tianlu1677** [botorange/xiaoju#15]
```js
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://ex-api.botorange.com/message/send?token=xxx",
  "method": "POST",
  "headers": {
    "content-type": "application/x-www-form-urlencoded"
  },
  "data": {
    "chatId": "5d270146bd6faa1c4e0c0a24",
    "token": "xxxx",
    "messageType": 1,
    "payload[text]": "我们"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```
When I use postman to send message I got this error.

```
{
  "error": "Validation Failed",
  "detail": [
    {
      "message": "should be an integer",
      "code": "invalid",
      "field": "messageType"
    }
  ]
}
```

**Comment by windmemory** [comment]
The `messageType` needs to be an integer. I think you need to check your post method, it might mess up with the data type, and changed it to be a string.

Try to change `content-type` to be `application/json`

**Comment by tianlu1677** [comment]
Becase when you receiver params，it always string. I guess you should parse string to integer. 

I try Content-Type 'application/json', or form-data.  Could you give me a simple example? Thanks. @windmemory

**Comment by windmemory** [comment]
It is not params, it should be body, because this is a post request.

**Comment by tianlu1677** [comment]
![image](https://user-images.githubusercontent.com/2594920/61103921-ac138e80-a4a6-11e9-8082-0f575ebe8dc1.png)

**Comment by windmemory** [comment]
type needs to be application json.
You can start a dev server and post the message youself to your server, and see if the data type you sent is right.

**Comment by tianlu1677** [comment]
Thank you.  I success. We should data.to_json and content_type: 'application/json'
