### ISSUE TITLE
关于 chatId 的获取

### ISSUE THREAD

**Issue by fengliu222** [botorange/xiaoju#23]
在 API Doc 中有写道「 chat id 需要提前获取」。

在使用 xiaoju 服务时，有哪个地方能够暴露出现有 chat 的列表吗？如果不提供 chat 列表的 API，开发者如何得知 chat api 并使用发送消息的 API 呢？

**Comment by iguxiaobei** [comment]
https://github.com/botorange/xiaoju/wiki/API-Doc

可以看下我们的文档，接收到的消息里面，有chatId，你也可以通过

[获取联系人列表](https://ex-api.botorange.com/contact/list)
[获取群列表](https://ex-api.botorange.com/room/list)
获取到的联系人和群信息里面，也都有chatId

**Comment by fengliu222** [comment]
Thanks!
