### ISSUE TITLE
关于wiki 中 API doc 说明的一些问题

### ISSUE THREAD

**Issue by cr4fun** [botorange/xiaoju#24]
1、严格json格式
需要有英文的双引号，不是中文，也不是原始javascript或ts对象。
2、给的例子应该经过测试是拿来就能用的
如，发送时，messageType为0，是文本回复。但是wiki上面写的是1。
3、最好给出文本、图片、url回复的具体示例代码，而不是图省事儿给出enum。
4、格式中带有问号的，具体应该变成json的形式  
roomTopic?: string,    这种在json中是不能被解析的

**Comment by iguxiaobei** [comment]
@cr4fun 我们更新了一版。

**Comment by lijiarui** [comment]
@cr4fun 感谢指出问题，如果么有问题，可以关掉这个issue了， 谢谢~
