### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by yuler** [botorange/xiaoju#25]
[wiki 接收消息](https://github.com/juzibot/xiaoju/wiki/API-Doc#%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF)

```js
"contactId": "wxid_rr9ej1o8xv9h21",
```

返回的是用户微信真实的 ID，不可以直接用于 @

[wiki 发送消息](https://github.com/juzibot/xiaoju/wiki/API-Doc#%E5%8F%91%E6%B6%88%E6%81%AFurl%E4%B8%BA-httpsex-apibotorangecommessagesend)

当 `mention` 字段输入了无效的，并不报错

**Comment by iguxiaobei** [comment]
1. wiki 接收消息返回的是用户微信真实的 ID，不可以直接用于 @
这个只有在给群发消息的时候，才能at群里的人
2. 当 mention 字段输入了无效的，并不报错
这个确实，因为底层不报错，这个mention是在往群里发消息的时候，@群成员用的，必须是群成员的wxid

**Comment by yuler** [comment]
可以再 Wiki 上注释下

**Comment by iguxiaobei** [comment]
好的，我们更新下文档，解释下这个字段。

**Comment by yuler** [comment]
多谢
