### ISSUE TITLE
关闭问题

### ISSUE THREAD

**Issue by gowithwind** [botorange/xiaoju#28]

**Comment by gowithwind** [comment]
偶发出现调用发送,但实际消息未送到群内

**Comment by lijiarui** [comment]
需要给出完整的日志信息，建议复制粘贴日志内容到这里，以及对应的代码片段，因为这些日志是和我们业务完全没有关系的，这样给出很难排查。

**Comment by gowithwind** [comment]
这个问题就是ssl连接问题了. 代码没有改动就是调用发送消息. 不明白还要什么日志

**Comment by gowithwind** [comment]
SSLError: EOF occurred in violation of protocol

具体原因可能是网络故障,证书问题等.  需要看下当时你们的服务(如果有很多家使用) 调查下其他家是否这个时段存在问题. 否则只能当做网络故障处理了.
